// var name = ["razu", "rakib", "juwel", "rahi", "rashed", "tamim", "samim"];
// var ami = name.length;
// console.log(ami);
// console.log(name);
// var quantity = name.indexOf("rakib");
// console.log(quantity);
// var position = name[5];
// console.log(position);
// name.pop();
// console.log(name);

var numbers = [20, 30, 40, 50, 60, 70];
var amarAge = numbers[0];
numbers.push(30);
console.log(amarAge);
console.log(numbers);
numbers.pop();
console.log(numbers);
numbers.shift();
console.log(numbers);
numbers.unshift(123, 30);
console.log(numbers);
let fivePosition = numbers.indexOf(50);
console.log(fivePosition);
